ERROR_INVALID_NAME = "Must be 1-32 characters and contain only letters, digits, '-', '_', or '.' and not include '^' or '='."
ERROR_INVALID_DATE = "Invalid date format. Please enter the date in YYYY-MM-DD format."
ERROR_INVALID_KEY_NAME = "this key name already in the system. choose diffrent type of key name"
ERROR_DATA_ALREADY_IN_THE_SYSTEM = "this data already in the system. "
PROMPT_FOR_TEMPLATE = "(type 'list' to list all allowed templates, prefix your template with the characters 'ad-hoc-' to enter a free form template): "
ERROR_TEMPLATE_DISALLOWED = "The chosen template is disallowed, pleasechoose another one. You may type 'list' to list allowed templates"
ERROR_TEMPLATE_NOT_KNOWN = "This template is not known. To use ad-hoc template prefix its name with 'ad-hoc-'"
ERROR_INVALID_BOOLEAN = "Invalid input. Please enter 'True' or 'False'"
ERROR_REMOVE_NOT_BREAKABLE = "This key is not breakable, so it cannot be removed."
